# Generated by Django 5.1.4 on 2025-01-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prompt',
            new_name='Promt',
        ),
    ]
